spring:
  config:
    activate:
      on-profile: "local"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${LOCAL_DB_URL}?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&setTimezone=Asia/Seoul # 변경해주세요
    username: ${LOCAL_USERNAME}
    password: ${LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            provider: kakao
            redirect-uri: ${LOCAL_REDIRECT}
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id